### ISSUE TITLE
Plan the update for WP 5.6

### ISSUE THREAD

**Issue by azaozz** [WordPress/jquery-migrate-helper#16]
Following up on couple of discussions on Slack, Enable jQuery Migrate Helper will have to be updated to support the changes in WP 5.6. Would be good to have a list of what needs to be done for the usage, workflow, and the UI.

Current ideas:
- Make the plugin even more "vocal", perhaps remove "snoozing" of the main warning, perhaps output the `JQMIGRATE` warnings on all admin screens or even on the front-end when an admin is logged-in. Also perhaps email the log to the site admin(s) weekly.
- Add a warning (on the Dashboard) that the plugin may not be needed any more when there are no more log entries for some time.
- Edit the main warning message to better explain the role of the plugin and the needed next steps.

**Comment by Clorith** [comment]
I agree that it should be more vocal, if they're now being "backported" to jQuery 1.x, then make the main warning non-dismissible is the ideal approach.

I've been thinking a bit about the code changes that we could probably do as well, to make this as frictionless as possible.

- Bundle jQuery `1.12.4-wp` with the plugin
- Add a global error handler for uncaught exceptions, to detect functions jQuery Migrate would have previously warned about
- If an old function is detected, set a legacy-flag
- If a legacy flag is set, override the core bundled jQuery version with the one bundled in the plugin
- Make warnings persistent and non-dismissive

I'm leaning towards the automated legacy flag approach, as I'm not a fan of user options that to most would mean nothing.

I'm not a fan of the downgrade path, but there's an indication it may be beneficial for now.

Alternative path:
- Do **not** bundle jQuery `1.12.4-wp`
- If migrate plugin is enabled make warnings persistent and non-dismissible
- Add a global error handler to detect functions jQuery Migrate would have previously warned about
- Surface fatal errors like we do with migrate ones today, since they are fatals we would have stack traces straight away much like the migrate stack right now.

**Comment by Clorith** [comment]
As work progresses nicely in the [wp-5.6 branch](https://github.com/WordPress/jquery-migrate-helper/tree/feature/wp-5.6), I'll outline what I've done here:

jQuery 1.12.4-wp has been bundled with the plugin.

jQuery Migrate 3.3.2-wp is also bundled, this means it _will_ show warnings from core as well, but I think that's acceptable right now, they are just deprecations, and it will help with core approaches to getting things to a good state as well I believe.

The first time a previously deprecated, now removed, function tries to run, a global error handler picks it up, and sends an ajax request. If this is a jQuery feature that has been removed, then the site will automatically downgrade to 1.12.4-wp (this will **only** happen the first time, if the version is changed later on, any fatal errors will remain fatal errors)

I've also added a page under Tools in the main menu (and reduced the admin bar menu to link here), the options of changing versions, and displaying dashboard notices were becoming too obscure to reliably sit up there.

This also allowed for a logs page, instead of an admin notice for this, a page has been dedicated, allowing for some more flexibility in the report output as well, namely:
- It now tells what plugin or theme (if discernable)
- It links to the plugin or themes URL (or their authors URL if that isn't defined)
- It is more direct in explaining that the source of a deprecation is unknown if it is printed inline on a page.

Also added `jquery-migrate` as a dependency for the deprecation handler script the plugin introduces, previously only `jquery` was added, and it appears there's some inconsistencies with getting dependencies in order there (as previous by a few tickets to check for `migrateWarn` before using it)

A Site Health check has been added to show if a good (3.5) version of jQuery is running, if 1.12.4-wp is enabled, it'll be marked as a critical task to fix.

---

What's left:

- Non-dismissive admin notice when using 1.12.4-wp
- WP_Cron event to send an update to the site admin on their jQuery status (this might need to be an opt-in for existing users)
- Better explanation in admin notice

**Comment by Clorith** [comment]
WP_Cron events are now in place, a weekly email (and the initial one being sent a day after updating the plugin, for those who've already been capturing deprecations from the previous update).

The email will also be sent if no deprecations are captured in a week, and will then encourage the removal of the plugin instead.

![preview of example email](https://user-images.githubusercontent.com/468735/99891114-b5019c00-2c66-11eb-9be5-f852e8db8ceb.png)

**Comment by Clorith** [comment]
Commit e38b812a26bd23bfa6cc3a101ca259dfed924092 introduced copy-editing from our resident wordsmith (props @marybaum), I'm moving to close this issue, as all items have been addressed. Further refinements can still happen, but should then be done in individual tickets.

For now the current strings are available in the development branch of the plugin directory as well so [polyglots can translate it](https://translate.wordpress.org/projects/wp-plugins/enable-jquery-migrate-helper/), and any typos can be caught pre-release.
