### ISSUE TITLE
Disable automatic mails

### ISSUE THREAD

**Issue by bodograumann** [WordPress/jquery-migrate-helper#28]
I don’t want all the site admins in my wordpress network to get weekly mails that only confuse them.
Please disable the notification mails by default.

**Comment by fliespl** [comment]
You can use filters to disable them until feature is implemented :)

**Comment by doit-jochem** [comment]
Hi All! 

At our business we have more then a few Wordpress environments. Disabling the automatic mails is a must for us because our customers are getting the mails now and are getting confused. Adding the filters in each project would be time consuming. I also prefer to let the plugin codebase maintain the most of the functionality and only in worst-cases add the filters in each project. 

Is there a solution in progress? 

Thanks in advance.

With kind regards,

Jochem

**Comment by Clorith** [comment]
I'll sound a bit direct here, but you could also resolve the emails by upgrading, or replacing, the plugins or themes that are causing deprecation notices, this would also ensure that sites do not suddenly lose functionality unexpectedly in the future.

**Comment by jmslbam** [comment]
I found out these lines helped.
```
remove_action( 'enable_jquery_migrate_helper_notification', array( 'jQuery_Migrate_Helper', 'scheduled_event_handler' ) );
remove_action( 'admin_bar_menu', array( 'jQuery_Migrate_Helper', 'admin_bar_menu' ), 100 );
remove_action( 'admin_notices', array( 'jQuery_Migrate_Helper', 'admin_notices' ) );
```

**Comment by Clorith** [comment]
As the notifications system is an integral, and intended, part of the plugins behavior. I'm closing out this issue at this time.

The official remediation from our side is to address any warnings of deprecated code, so that the plugin may be removed.
